### ISSUE TITLE
`truffle test` does not return an error if devent is not running

### ISSUE THREAD

**Issue by nitper** [0xProject/dev-tools-truffle-example#2]
Thanks for this demo project - I was able to integrate it into my existing truffle project and it's mostly working well.

However, `truffle test` no longer returns an error code if the devnet is not running.
```bash
/dev-tools-truffle-example$ yarn test
yarn run v1.13.0
$ truffle test
Done in 11.19s.

/dev-tools-truffle-example$ echo $?
0
```

truffle usually behaves like this:
```bash
$ truffle test
Could not connect to your Ethereum client. Please check that your Ethereum client:
    - is running
    - is accepting RPC connections (i.e., "--rpc" option is used in geth)
    - is accessible over the network
    - is properly configured in your Truffle configuration file (truffle.js)

Truffle v5.0.1 (core: 5.0.1)
Node v11.7.0

$ echo $?
1
```

**Comment by ravidsrk** [comment]
@nitper You must start `ganache` before you run `truffle test`

**Example command**
```
ganache-cli -p 9545 --accounts 30 > /dev/null
```

**Comment by nitper** [comment]
I intentionally did not start `ganache` (or [`devnet`](https://github.com/0xProject/0x-monorepo/tree/development/packages/devnet) as this project requires).

With standard truffle, `truffle test` returns an error code if it cannott connect to your web3 provider, which is expected.

With *this* truflle project (with the 0x devtools integrated), `truffle test` *returns success* if it can't connect to your web3 provider. **This is incorrect behavior.**

**Comment by WyseNynja** [comment]
Agreed that this is incorrect behavior.

I think this might be because `provider.start();` in truffle-config.js doesn't have any sort of checks that it succeeded.

**Comment by LogvinovLeon** [comment]
Good catch. Fixed now. https://github.com/0xProject/dev-tools-truffle-example/commit/79b2004e32f0f1c4b2734a3767965b5c6cf968fc
