### ISSUE TITLE
What is the best way to reset the geth instance?

### ISSUE THREAD

**Issue by WyseNynja** [0xProject/dev-tools-truffle-example#3]
I ran my tests twice and a bunch of them failed the second time while checking balances. I was using ganache-cli which automatically resets the database after tests finish. Is there a way to do that with the geth instance recommended here? For now I can manually restart it, but it's a lot slower than ganache.

**Comment by LogvinovLeon** [comment]
In ganache you have snapshots. In Geth you have the `debug_setHead` method. it reverts blocks and acts essentially the same way as snapshots.
Check out that: https://github.com/0xProject/0x-monorepo/blob/development/packages/dev-utils/src/blockchain_lifecycle.ts
And that: https://github.com/0xProject/0x-monorepo/blob/development/packages/web3-wrapper/src/web3_wrapper.ts#L657

Unfortunately in official Geth this method is broken. We've fixed that in our fork. But it's taking a really long time to get those changes upstream.

Our fork also has time travel, if you need that.

Please feel free to reopen if you have any more questions.
